// Publish Markdown posts to a GitHub repository via the REST "Contents" API.
// Native fetch, no Octokit.

const API = "https://api.github.com";
const USER_AGENT = "youtube-to-article";

export interface PublishToGitHubInput {
  title: string;
  content: string;
  tags: string[];
  slug: string;
  description?: string;
  date?: string;
  /** Defaults to the GITHUB_TOKEN env var. */
  token?: string;
  /** Defaults to GITHUB_OWNER / GITHUB_REPO / GITHUB_BRANCH env vars. */
  owner?: string;
  repo?: string;
  branch?: string;
  /** Directory inside the repo. Defaults to `content/posts`. */
  dir?: string;
}

export interface PublishToGitHubResult {
  path: string;
  url: string;
  commitSha: string | null;
}

export class GitHubPublishError extends Error {
  constructor(
    message: string,
    readonly status: number,
  ) {
    super(message);
    this.name = "GitHubPublishError";
  }
}

function config(input: {
  owner?: string;
  repo?: string;
  branch?: string;
  dir?: string;
}) {
  const owner = input.owner ?? process.env.GITHUB_OWNER;
  const repo = input.repo ?? process.env.GITHUB_REPO;
  if (!owner || !repo) {
    throw new GitHubPublishError(
      "No GitHub target repo. Connect GitHub or pass owner/repo.",
      500,
    );
  }
  return {
    owner,
    repo,
    branch: input.branch ?? process.env.GITHUB_BRANCH ?? "main",
    dir: (input.dir ?? process.env.GITHUB_CONTENT_DIR ?? "content/posts").replace(
      /^\/|\/$/g,
      "",
    ),
  };
}

function headers(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "User-Agent": USER_AGENT,
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

// Maps GitHub status codes to actionable messages.
function friendlyError(res: Response, body: unknown): GitHubPublishError {
  const message =
    (body as { message?: string })?.message ?? `GitHub request failed`;
  if (res.status === 401) {
    return new GitHubPublishError(
      "GitHub token is invalid or expired. Generate a new PAT and reconnect.",
      401,
    );
  }
  if (res.status === 403) {
    const remaining = res.headers.get("x-ratelimit-remaining");
    if (remaining === "0") {
      const reset = Number(res.headers.get("x-ratelimit-reset") ?? 0);
      const when = reset ? new Date(reset * 1000).toISOString() : "later";
      return new GitHubPublishError(
        `GitHub rate limit exceeded. Resets at ${when}.`,
        403,
      );
    }
    return new GitHubPublishError(
      "GitHub permission denied. The token needs Contents: Read and write access to the repo.",
      403,
    );
  }
  if (res.status === 404) {
    return new GitHubPublishError(
      "GitHub repo or branch not found. Check the repo name and GITHUB_BRANCH.",
      404,
    );
  }
  if (res.status === 409 || res.status === 422) {
    return new GitHubPublishError(
      `GitHub rejected the file update (${res.status}): ${message}`,
      422,
    );
  }
  return new GitHubPublishError(`GitHub request failed (${res.status}): ${message}`, res.status);
}

function encodePath(path: string): string {
  return path.split("/").map(encodeURIComponent).join("/");
}

// Verifies the token and ensures the target repo exists, creating a private
// repo (with an initial commit) when missing. Returns its `owner/name`.
export async function ensureGitHubRepo(
  token: string,
  repoName?: string,
): Promise<{ login: string; fullName: string }> {
  const userRes = await fetch(`${API}/user`, { headers: headers(token) });
  const user = (await userRes.json().catch(() => ({}))) as {
    login?: string;
    message?: string;
  };
  if (!userRes.ok) throw friendlyError(userRes, user);
  const login = user.login ?? "";
  if (!login) {
    throw new GitHubPublishError("Could not resolve GitHub account", 401);
  }

  const name = repoName?.trim() || process.env.GITHUB_REPO_NAME || "articles";

  const existing = await fetch(`${API}/repos/${login}/${name}`, {
    headers: headers(token),
  });
  if (existing.ok) {
    const json = (await existing.json()) as { full_name?: string };
    return { login, fullName: json.full_name ?? `${login}/${name}` };
  }
  if (existing.status !== 404) {
    throw friendlyError(existing, await existing.json().catch(() => ({})));
  }

  const created = await fetch(`${API}/user/repos`, {
    method: "POST",
    headers: headers(token),
    body: JSON.stringify({
      name,
      private: true,
      auto_init: true,
      description: "Articles generated by YouTube to Article",
    }),
  });
  const json = (await created.json().catch(() => ({}))) as {
    full_name?: string;
  };
  if (!created.ok) throw friendlyError(created, json);

  return { login, fullName: json.full_name ?? `${login}/${name}` };
}

function yamlString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Standard Markdown with YAML frontmatter.
export function buildMarkdownFile(input: {
  title: string;
  content: string;
  tags: string[];
  slug: string;
  description?: string;
  date?: string;
}): string {
  const date = input.date ?? new Date().toISOString();
  const frontmatter = [
    "---",
    `title: "${yamlString(input.title)}"`,
    `date: "${date}"`,
    `description: "${yamlString(input.description ?? "")}"`,
    `tags: [${input.tags.map((t) => t.trim()).filter(Boolean).join(", ")}]`,
    `slug: "${yamlString(input.slug)}"`,
    "---",
  ].join("\n");

  return `${frontmatter}\n\n${input.content}\n`;
}

// Fetches the current file's blob sha, or null when the file doesn't exist yet.
async function getExistingSha(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch: string,
): Promise<string | null> {
  const url = `${API}/repos/${owner}/${repo}/contents/${encodePath(path)}?ref=${encodeURIComponent(branch)}`;
  const res = await fetch(url, { headers: headers(token) });

  if (res.status === 404) return null;
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw friendlyError(res, body);
  }

  const json = (await res.json()) as { sha?: string };
  return json.sha ?? null;
}

export async function publishArticleToGitHub(
  input: PublishToGitHubInput,
): Promise<PublishToGitHubResult> {
  if (!input.slug) {
    throw new GitHubPublishError("A slug is required to build the file path", 400);
  }
  const token = input.token ?? process.env.GITHUB_TOKEN;
  if (!token) {
    throw new GitHubPublishError(
      "No GitHub token. Connect GitHub or set GITHUB_TOKEN.",
      401,
    );
  }
  const { owner, repo, branch, dir } = config(input);
  const path = `${dir}/${input.slug}.md`;

  // Update in place when the post already exists, otherwise create it.
  const sha = await getExistingSha(token, owner, repo, path, branch);

  const markdown = buildMarkdownFile(input);
  const content = Buffer.from(markdown, "utf8").toString("base64");

  const res = await fetch(
    `${API}/repos/${owner}/${repo}/contents/${encodePath(path)}`,
    {
      method: "PUT",
      headers: headers(token),
      body: JSON.stringify({
        message: `${sha ? "Update" : "Add"} post: ${input.slug}`,
        content,
        branch,
        ...(sha ? { sha } : {}),
      }),
    },
  );

  const json = (await res.json().catch(() => ({}))) as {
    content?: { html_url?: string };
    commit?: { sha?: string };
  };
  if (!res.ok) throw friendlyError(res, json);

  return {
    path,
    url: json.content?.html_url ?? "",
    commitSha: json.commit?.sha ?? null,
  };
}
